### ISSUE TITLE
icons on the left side of the shelf

### ISSUE THREAD

**Issue by Tealk** [Etenil/minimize-shelf#1]
Hi,

is it possible to put the icons on the left side of the shelf?

**Comment by blfpd** [comment]
Hi @Tealk, sure, we’ll add more parameters in near future!

**Comment by blfpd** [comment]
Well… It’s implemented in https://github.com/batisteo/minimize-shelf/releases/tag/v7 ! :tada:

You might need to re-log in your session after the update, and also re-enable the extension after choosing <kbd>Left</kbd>.
